# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: ActionScript 3 CI

# Github worflows do not support actionscript directly.
# However the build uses ant, which is usually used to build java projects.
# The ant task (mxmlc) provided by the flex SDK (ant/lib/flexTasks.jar) is used to build the project.

on:
  push:
    # Just so the CI won't complain about Vanilla+ failing, since V+ isn't configured for CI.
    branches-ignore: [ VanillaPlus ]
  pull_request:
    branches: [ master ]

env:
  # tell the build file where to find the flex SDK
  FLEX_HOME: "build-dep/bin/flex/"
  # this is to trick the flash player into thinking it is running on a desktop
  DISPLAY: ":1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # different configurations that should be built
        build: [ release, debug ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Update CoC version in sonar configuration
      run: devTools/ci/update-sonar-version.sh

  # Run sonar scan if a build on master succeeds. This generates project code quality stats and lists possible issues
  sonarcloud:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORG }}
      env:
        # provided by Github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # This needs to be set in the Github repository. Repository settings > secrets > new secret
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
